<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>DesktopPetUi</RootNamespace>
    <AssemblyName>desktop-pet-ui</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Platforms>x64</Platforms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <DebugType>embedded</DebugType>
    <NoWarn>WFAC010</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Speech" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\plugin-api\DesktopPetUi.PluginApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\character\**" CopyToOutputDirectory="PreserveNewest" LinkBase="character" ExcludeFromSingleFile="true" />
  </ItemGroup>

</Project>